spring:
  sql.init.schema-locations: classpath:schema-h2.sql
  config.activate.on-profile: default
  web.resources.static-locations: file:./app/
cds:
  datasource.auto-config.enabled: false

---
spring:
  config.activate.on-profile: sqlite
  sql:
    init:
      mode: never
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  web.resources.static-locations: file:./app/
cds:
  datasource.auto-config.enabled: false
