server:
  port: 8090
spring:
  application:
    name: "freight_cost"
  config.activate.on-profile: default
  sql:
    init:
      mode: never
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  web.resources.static-locations: file:./app/
cds:
  datasource.auto-config.enabled: false


